name: test-docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image only for e2e tests
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: ltsuda/playwright-study:e2e
          load: true
          push: false

      - name: Run e2e on docker
        uses: addnab/docker-run-action@v3
        with:
          image: ltsuda/playwright-study:e2e
          run: npx playwright test --grep-invert '@visual' --reporter 'dot'


  run_visual:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image only for visual tests
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.visual
          tags: ltsuda/playwright-study:visual
          load: true
          push: false

      - name: Run @visual on docker
        uses: addnab/docker-run-action@v3
        with:
          image: ltsuda/playwright-study:visual
          run: npx playwright test --grep @visual --project 'chromium-hd' --reporter 'dot'
