name: test-docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image for the Webapp
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.webapp
          tags: ltsuda/playwright-study:webapp
          load: true
          push: false

      - name: Build image only for e2e tests
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: ltsuda/playwright-study:e2e
          load: true
          push: false

      - name: Create docker network for container communications
        run: docker network create net-webapp

      - name: Start Webapp container and wait until app is running
        run: |
          docker run --network=net-webapp --name=web -p 3000:3000 --rm -d \
            --health-cmd='curl --fail http://localhost:3000' \
            --health-interval=5s \
            --health-retries=3 \
            --health-start-period=10s \
            --health-timeout=60s \
            ltsuda/playwright-study:webapp

      - name: Get webapp container's health and exits if unhealthy
        run: |
          for i in {1..6}; do if [ $(docker inspect --format='{{json .State.Health.Status}}' web) == '"healthy"' ]; then echo $? && break; else sleep 10 && QUIT=1;fi;done
          if [[ -v QUIT ]] && [ $QUIT -eq 1 ]; then exit 1;fi;

      - name: Start Testing container
        run: |
          docker run --network=net-webapp --name=testing --rm \
          ltsuda/playwright-study:e2e \
          npx playwright test --grep-invert '@visual' --reporter 'dot' -c playwright.config-docker.js

  run_visual:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image for the Webapp
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.webapp
          tags: ltsuda/playwright-study:webapp
          load: true
          push: false

      - name: Build image only for visual tests
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: ltsuda/playwright-study:visual
          load: true
          push: false

      - name: Create docker network for container communications
        run: docker network create net-webapp

      - name: Start Webapp container and wait until app is running
        run: |
          docker run --network=net-webapp --name=web -p 3000:3000 --rm -d \
            --health-cmd='curl --fail http://localhost:3000' \
            --health-interval=5s \
            --health-retries=3 \
            --health-start-period=20s \
            --health-timeout=120s \
            ltsuda/playwright-study:webapp

      - name: Get webapp container's health and exits if unhealthy
        run: |
          for i in {1..6}; do if [ $(docker inspect --format='{{json .State.Health.Status}}' web) == '"healthy"' ]; then echo $? && break; else sleep 2 && QUIT=1;fi;done
          if [[ -v QUIT ]] && [ $QUIT -eq 1 ]; then exit 1;fi;

      - name: Start Testing container for visual testing
        run: |
          docker run --network=net-webapp --name=testing --rm \
            ltsuda/playwright-study:visual \
            npx playwright test --grep @visual --project 'chromium-hd' --reporter 'dot'
